# Generated by Django 5.0.3 on 2024-03-24 07:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_rename_todo_todolist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='todolist',
            new_name='todolistx',
        ),
    ]
