# Generated by Django 5.0.3 on 2024-03-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0005_alter_todo_options_alter_todo_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ProfilePicture',
            field=models.ImageField(blank=True, default='Default.png', null=True, upload_to='NMS/Cleaning/AppTest/media'),
        ),
    ]
